### ISSUE TITLE
Webring Widget floats over <hr> and bottom icons

### ISSUE THREAD

**Issue by richjsouth** [whitep4nth3r/mk2-p4nth3rblog#101]
When not full screen, the Webring Widget floats over the HR at the bottom of the page and everything below it.  Tested on Firefox and Chrome on Windows 10 ( work laptop, so not my fault ;-) ).  Not sure if this is expected behaviour or not.  -  This is my first 'Issue' submission on GitHub so please forgive me if it's not done correctly.  Love watching you on Twitch!  Feel free to close this if it's nonesense.

See image:
![ff](https://user-images.githubusercontent.com/30663346/207613036-496d9a57-3dfd-4872-91c8-995b6821165a.png)

**Comment by whitep4nth3r** [comment]
Thanks @richjsouth, good catch! This is really helpful and I will fix it on stream on Friday.
