### ISSUE TITLE
Broken links on about page

### ISSUE THREAD

**Issue by tdrayson** [whitep4nth3r/mk2-p4nth3rblog#117]
On the [about page](https://whitep4nth3r.com/about/) the following links are broken:

- [**Jamstack Conf 2021 Community Creator Award**](https://jamstackconf.com/jammies/) has moved to https://jamstack.org/conf/jammies/
- [fun and silly websites](https://randomcodegenerator.lol/) (random code generator) - SSL received a record that exceeded the maximum permissible length.

**Comment by whitep4nth3r** [comment]
Thanks! Found the actual Jammies Awards page [here](https://2021.jamstackconf.com/jammies/).
